localapp/models.py
from . import db
from flask_login import UserMixin
from flask_bcrypt import Bcrypt

bcrypt = Bcrypt()

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())

    def set_password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password).decode('utf-8')

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

localapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
import os

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object('localapp.config.Config')

    db.init_app(app)
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    
    login_manager.init_app(app)
    login_manager.login_view = 'main.login'
 
    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    from .routes import main
    app.register_blueprint(main)

    with app.app_context():
        hashed_password = bcrypt.generate_password_hash(os.getenv('DATABASE_PW')).decode("utf-8")

        from . import models
        db.create_all()

        user_exists = User.query.filter_by(email=os.getenv('DATABASE_EMAIL')).first()
        if not user_exists:
            new_user = User(username=os.getenv('DATABASE_USER'), email=os.getenv('DATABASE_EMAIL'), password_hash=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            print("User created successfully!")
        else:
            print("User already exists. Skipping insert.")

    return app

localapp/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from . import db, bcrypt
from .models import User


main = Blueprint("main", __name__)


@main.route('/')
def home():
    if current_user.is_authenticated:
       return redirect(url_for('main.welcome'))
    else:
        return redirect(url_for('main.login'))



@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = bcrypt.generate_password_hash(request.form['password']).decode('utf-8')
        user = User(username=username, email=email, password_hash=password)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html')



@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        flash('test', 'danger')
        user = User.query.filter_by(username=request.form['username']).first()
        #if user and bcrypt.check_password_hash(user.password_hash, request.form['password']):
        if user and user.check_password(request.form['password']):
            flash('OK', 'success')
            login_user(user)
            return redirect(url_for('main.welcome'))
        else:
            flash('Invalid credentials', 'danger')
    return render_template('login.html')



@main.route('/welcome')
@login_required
def welcome():
    user = User.query.filter(User.id==current_user.id).first()
    return render_template('welcome.html', user=user)



@main.route('/logout')
def logout():
    logout_user()
    flash('You have logged out.', 'info')
    return redirect(url_for('main.login'))

localapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
    
    <main>
        {% block content %}{% endblock %}
    </main>

    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}" defer></script>
</body>
</html>

localapp/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container">
    <h2>Login</h2>
    <form method="POST">
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <button type="submit">Login</button>
    </form>
    <p>
        Alternatively: <a href="{{ url_for('main.register')}}">Register</a>
    </p>
</div>
{% endblock %}

localapp/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="container">
    <h2>Register</h2>
    <form method="POST">
        <input type="text" name="username" placeholder="Username" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="password" name="password" placeholder="Password" required>
        <button type="submit">Register</button>
    </form>
</div>
{% endblock %}

localapp/templates/welcome.html
{% extends 'base.html' %}
{% block title %}Welcome{% endblock %}

{% block content %}
<div class="container">
    <h2>Welcome {{user.username}}</h2>
    <p>
        You may wish to: <a href="{{ url_for('main.logout')}}">Logout</a>
    </p>
</div>
{% endblock %}